CREATE TABLE EMPLOYEE (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	first_name varchar(255) not null,
	manager_id BIGINT
);

-- create sequence employee_sequence start with 1 increment by 1;

insert into EMPLOYEE (id, first_name, manager_id) values (100, 'Alan', 150);
insert into EMPLOYEE (id, first_name, manager_id) values (220, 'Martin', 100);
insert into EMPLOYEE (id, first_name, manager_id) values (150, 'Jamie', null);
insert into EMPLOYEE (id, first_name, manager_id) values (275, 'Alex', 100);
insert into EMPLOYEE (id, first_name, manager_id) values (400, 'Steve', 150);
insert into EMPLOYEE (id, first_name, manager_id) values (190, 'David', 400);
